apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::014071048720:role/finance-platform-dev-minimal-eks-node-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-07T02:17:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1029"
  uid: f8803d95-d24b-4cdd-8b59-b1738d029518
