apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finance-platform-local-ingress
  namespace: finance-platform
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          - path: /api/upload(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: upload-service
                port:
                  number: 80
          - path: /api/transactions(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: analytics-service
                port:
                  number: 80
