apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::014071048720:role/finance-platform-dev-minimal-eks-node-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-07T07:25:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "962"
  uid: 883c2ee1-6fba-420e-bb23-4529fa6eb01f
