variable "environment"            { default = "production" }
variable "aws_region"             { default = "ap-south-1" }
variable "vpc_cidr"               { default = "10.0.0.0/16" }
variable "availability_zones"     { default = ["ap-south-1a", "ap-south-1b", "ap-south-1c"] }
variable "eks_node_instance_type" { default = "t3.small" }
variable "eks_min_nodes"          { default = 2 }
variable "eks_max_nodes"          { default = 10 }
variable "rds_instance_class"     { default = "db.t3.micro" }
variable "db_name"                { default = "financedb" }
variable "github_org"             { default = "your-github-org" }
variable "github_repo"            { default = "finance-platform" }
variable "allowed_origins"        { default = ["https://yourdomain.com"] }
